wallpaper {
    monitor = desc:LG Electronics LG FULL HD 0x01010101 
    path = /home/tusk/Downloads/DarkWallpapers/gold/a_yellow_moon_in_the_sky.png
    fit_mode = cover
}

wallpaper {
    monitor = desc:BOE NE160WUM-NX4
    path = /home/tusk/Downloads/DarkWallpapers/gold/a_yellow_moon_in_the_sky.png
    fit_mode = cover
}

wallpaper {
    monitor = desc:Ancor Communications Inc ASUS VP228 G6LMTF032613
    path = /home/tusk/Downloads/DarkWallpapers/gold/a_yellow_moon_in_the_sky.png
    fit_mode = cover
}
splash = false
