wallpaper {
    monitor = desc:LG Electronics LG FULL HD 0x01010101 
    path = /home/tusk/Downloads/DarkWallpapers/blackwhite/a_cat_looking_at_the_camera.png
    fit_mode = cover
}

wallpaper {
    monitor = desc:BOE NE160WUM-NX4
    path = /home/tusk/Downloads/DarkWallpapers/blackwhite/a_cat_looking_at_the_camera.png
    fit_mode = cover
}

wallpaper {
    monitor = desc:Ancor Communications Inc ASUS VP228 G6LMTF032613
    path = /home/tusk/Downloads/DarkWallpapers/blackwhite/a_cat_looking_at_the_camera.png
    fit_mode = cover
}
splash = false
